INSERT INTO public."TagTypes" ("Name")
VALUES
    ('Tính cách nhân vật chính'),
    ('Bối cảnh thế giới'),
    ('Lưu phái'),
    ('Thị giác');
    
INSERT INTO public."Tags" ("Name", "TagTypeId")
VALUES
    ('Điềm Đạm', 1),
    ('Nhiệt Huyết', 1),
    ('Vô Sỉ', 1),
    ('Thiết Huyết', 1),
    ('Nhẹ Nhàng', 1),
    ('Cơ Trí', 1),
    ('Lãnh Khốc', 1),
    ('Kiêu Ngạo', 1),
    ('Ngu Ngốc', 1),
    ('Giảo Hoạt', 1),
    ('Đông Phương Huyền Huyễn', 2),
    ('Dị Thế Đại Lục', 2),
    ('Vương Triều Tranh Bá', 2),
    ('Cao Võ Thế Giới', 2),
    ('Tây Phương Kỳ Huyễn', 2),
    ('Hiện Đại Ma Pháp', 2),
    ('Hắc Ám Huyễn Tưởng', 2),
    ('Lịch Sử Thần Thoại', 2),
    ('Võ Hiệp Huyễn Tưởng', 2),
    ('Cổ Võ Tương Lai', 2),
    ('Tu Chân Văn Minh', 2),
    ('Huyễn Tưởng Tu Tiên', 2),
    ('Hiện Đại Tu Chân', 2),
    ('Thần Thoại Tu Chân', 2),
    ('Cổ Điển Tiên Hiệp', 2),
    ('Viễn Cổ Hồng Hoang', 2),
    ('Đô Thị Sinh Hoạt', 2),
    ('Đô Thị Dị Năng', 2),
    ('Thanh Xuân Vườn Trường', 2),
    ('Ngu Nhạc Minh Tinh', 2),
    ('Thương Chiến Chức Tràng', 2),
    ('Giá Không Lịch Sử', 2),
    ('Lịch Sử Quân Sự', 2),
    ('Dân Gian Truyền Thuyết', 2),
    ('Lịch Sử Quan Trường', 2),
    ('Hư Nghĩ Võng Du', 2),
    ('Du Hí Dị Giới', 2),
    ('Điện Tử Cạnh Kỹ', 2),
    ('Thể Dục Cạnh Kỹ', 2),
    ('Cổ Võ Cơ Giáp', 2),
    ('Thế Giới Tương Lai', 2),
    ('Tinh Tế Văn Minh', 2),
    ('Tiến Hóa Biến Dị', 2),
    ('Mạt Thế Nguy Cơ', 2),
    ('Thời Không Xuyên Toa', 2),
    ('Quỷ Bí Huyền Nghi', 2),
    ('Kỳ Diệu Thế Giới', 2),
    ('Trinh Tham Thôi Lý', 2),
    ('Thám Hiểm Sinh Tồn', 2),
    ('Cung Vi Trạch Đấu', 2),
    ('Kinh Thương Chủng Điền', 2),
    ('Tiên Lữ Kỳ Duyên', 2),
    ('Hào Môn Thế Gia', 2),
    ('Dị Tộc Luyến Tình', 2),
    ('Ma Pháp Huyễn Tình', 2),
    ('Tinh Tế Luyến Ca', 2),
    ('Hệ Thống', 3),
    ('Lão Gia', 3),
    ('Bàn Thờ', 3),
    ('Tùy Thân', 3),
    ('Phàm Nhân', 3),
    ('Vô Địch', 3),
    ('Xuyên Qua', 3),
    ('Nữ Cường', 3),
    ('Khế Ước', 3),
    ('Trọng Sinh', 3),
    ('Hồng Lâu', 3),
    ('Học Viện', 3),
    ('Biến Thân', 3),
    ('Cổ Ngu', 3),
    ('Chuyển Thế', 3),
    ('Xuyên Sách', 3),
    ('Đàn Xuyên', 3),
    ('Phế Tài', 3),
    ('Dưỡng Thành', 3),
    ('Cơm Mềm', 3),
    ('Vô Hạn', 3),
    ('Mary Sue', 3),
    ('Cá Mặn', 3),
    ('Xây Dựng Thế Lực', 3),
    ('Xuyên Nhanh', 3),
    ('Nữ Phụ', 3),
    ('Vả Mặt', 3),
    ('Sảng Văn', 3),
    ('Xuyên Không', 3),
    ('Góc Nhìn Nam', 4),
    ('Góc Nhìn Nữ', 4),
    ('Ngôi Thứ Nhất', 4),
    ('Ngọt Sủng', 3),
    ('Ngự Thú', 3),
    ('Điền Viên', 3),
    ('Toàn Dân', 3),
    ('Linh Khí Khôi Phục', 2),
    ('Chư Thiên Vạn Giới', 2),
    ('Mỹ Thực', 3),
    ('Phản Phái', 3),
    ('Sau Màn', 3),
    ('Thiên Tài', 3),
    ('Nguyên Sinh Huyễn Tưởng', 2),
    ('Yêu Đương Thường Ngày', 2),
    ('Diễn Sinh Đồng Nhân', 2),
    ('Cáo Tiếu Thổ Tào', 2);
